import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from "next/font/google";

import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import TanstackProvider from "@/components/TanstackProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"], weight: ["200", "300", "400", "500", "700", "600", "800"], variable: "--font-inter" });

const kaoly = localFont({
  src: "./fonts/Kaoly.ttf",
  variable: "--font-kaoly",
  weight: "400 500 600 700 800 900",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${kaoly.variable} font-inter antialiased bg-off_white`}>
        <div className="w-full max-w-[1200px] mx-auto">
          <TanstackProvider>
            <Navbar />
            {children}
            <Footer />
          </TanstackProvider>
        </div>
      </body>
    </html>
  );
}
